application: angularjs-sample-sinmetal
version: 2013-05-19-21-35
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /list.html
  static_files: list.html
  upload: list.html

- url: /entry.html
  static_files: entry.html
  upload: entry.html

- url: /lib
  static_dir: lib

- url: /js
  static_dir: js

- url: /.*
  script: _go_app