application: angularjs-sample-sinmetal
version: 2013-05-19-21-35
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /lib
  static_dir: lib

- url: /html
  static_dir: html

- url: /script
  static_dir: script

- url: /style
  static_dir: style

- url: /.*
  script: _go_app